# Copyright Contributors to the Open Cluster Management project
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: governance-policy-addon-controller
  name: policy-addon-ctrl-leader-election-rolebinding
  namespace: {{ .Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: policy-addon-ctrl-leader-election-role
subjects:
  - kind: ServiceAccount
    name: policy-addon-ctrl-controller-manager
    namespace: {{ .Namespace }}
