# Copyright Contributors to the Open Cluster Management project
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: governance-policy-addon-controller
  name: policy-addon-ctrl-controller-manager
  namespace: {{ .Namespace }}
