# Copyright Contributors to the Open Cluster Management project
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: governance-policy-addon-controller
  name: policy-addon-ctrl-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - policy-encryption-key
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - addondeploymentconfigs
      - clustermanagementaddons
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - addon.open-cluster-management.io
    resourceNames:
      - config-policy-controller
      - governance-policy-framework
      - governance-standalone-hub-templating
    resources:
      - clustermanagementaddons/finalizers
      - managedclusteraddons/finalizers
    verbs:
      - update
  - apiGroups:
      - addon.open-cluster-management.io
    resourceNames:
      - config-policy-controller
      - governance-policy-framework
      - governance-standalone-hub-templating
    resources:
      - clustermanagementaddons/status
      - managedclusteraddons/status
    verbs:
      - patch
      - update
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - managedclusteraddons
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - addon.open-cluster-management.io
    resourceNames:
      - config-policy-controller
      - governance-policy-framework
      - governance-standalone-hub-templating
    resources:
      - managedclusteraddons
    verbs:
      - delete
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
      - get
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/approval
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    verbs:
      - approve
  - apiGroups:
      - cluster.open-cluster-management.io
    resourceNames:
      - id.k8s.io
    resources:
      - clusterclaims
    verbs:
      - get
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resourceNames:
      - config-policy-controller
      - governance-policy-framework
      - governance-standalone-hub-templating
    resources:
      - leases
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - policy.open-cluster-management.io
    resources:
      - policies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - policy.open-cluster-management.io
    resources:
      - policies/finalizers
    verbs:
      - update
  - apiGroups:
      - policy.open-cluster-management.io
    resources:
      - policies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - open-cluster-management:governance-standalone-hub-templating
    resources:
      - clusterrolebindings
    verbs:
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
    verbs:
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - open-cluster-management:config-policy-controller-hub
      - open-cluster-management:governance-standalone-hub-templating
      - open-cluster-management:policy-framework-hub
    resources:
      - clusterroles
      - rolebindings
    verbs:
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - work.open-cluster-management.io
    resources:
      - manifestworks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
