# Copyright Contributors to the Open Cluster Management project
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: config-policy-controller
spec:
  addOnMeta:
    description: Audits k8s resources and remediates violation based on configuration policies.
    displayName: Config Policy Addon
  supportedConfigs:
    - group: addon.open-cluster-management.io
      resource: addondeploymentconfigs
