# Copyright Contributors to the Open Cluster Management project
apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-propagator
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: governance-policy-propagator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: governance-policy-propagator
      labels:
        name: governance-policy-propagator
    spec:
      serviceAccountName: governance-policy-propagator
      containers:
        - name: governance-policy-propagator
          image: quay.io/open-cluster-management/governance-policy-propagator:{{ .BundleVersion.PolicyAddon }}
          command:
            - governance-policy-propagator
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8383
            - --leader-elect
            - --enable-webhooks=false
          ports:
            - containerPort: 8383
              protocol: TCP
              name: http
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: governance-policy-propagator
