# Copyright Contributors to the Open Cluster Management project
apiVersion: v1
kind: Service
metadata:
  name: governance-compliance-api
spec:
  ports:
    - port: 8384
      protocol: TCP
      targetPort: 8384
  selector:
    name: governance-policy-propagator
