# Copyright Contributors to the Open Cluster Management project
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: governance-policy-propagator
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - policy-encryption-key
    resources:
      - secrets
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps.open-cluster-management.io
    resources:
      - placementrules
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
      - placementdecisions
      - placements
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resourceNames:
      - cluster
    resources:
      - dnses
    verbs:
      - get
  - apiGroups:
      - policy.open-cluster-management.io
    resources:
      - placementbindings
      - policies
      - policyautomations
      - policysets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - policy.open-cluster-management.io
    resources:
      - policies/finalizers
      - policyautomations/finalizers
      - policysets/finalizers
    verbs:
      - update
  - apiGroups:
      - policy.open-cluster-management.io
    resources:
      - policies/status
      - policyautomations/status
      - policysets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - tower.ansible.com
    resources:
      - ansiblejobs
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
