# Copyright Contributors to the Open Cluster Management project
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multicluster-controlplane-agent
  namespace: {{.AgentNamespace}}
rules:
# create hub-kubeconfig and external-managed-registration/work secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
