# Copyright Contributors to the Open Cluster Management project
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicluster-operators-subscription
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
