# Copyright Contributors to the Open Cluster Management project
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-operators-subscription
subjects:
- kind: ServiceAccount
  name: multicluster-operators-subscription
  namespace: {{ .Namespace }}
roleRef:
  kind: ClusterRole
  name: multicluster-operators-subscription
  apiGroup: rbac.authorization.k8s.io
