# Copyright Contributors to the Open Cluster Management project
apiVersion: v1
kind: Service
metadata:
  labels:
    name: multicluster-operators-subscription
  name: multicluster-operators-subscription
  namespace: {{ .Namespace }}
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: multicluster-operators-hub-subscription
  sessionAffinity: None
  type: ClusterIP
