#!/usr/bin/env bash
# Copyright Contributors to the Open Cluster Management project
USAGE_MARKDOWN=../USAGE.md

function append {
  echo "$@" >> $USAGE_MARKDOWN
}

function addUsage {
  local command="$@"
  append
  append "## clusteradm $command"
  append '```'
  append "$(../clusteradm -h $@ 2>&1)"
  append '```'
  append "<sup><sub>[🔝 Back to top](#usage)</sub></sup>"
}

echo "<!-- Generated by hack/generateUsage.sh; DO NOT EDIT -->" > $USAGE_MARKDOWN
append "# Usage" 
append "### Index"
append "* [clusteradm](#clusteradm)"

SUBCOMMANDS=$(ls ../subcommands)
for subcommand in $SUBCOMMANDS
do
  name=$(basename $subcommand .sh)
  append "  * [${name}](#clusteradm-${name})" 
done

append "### Commands"

addUsage

SUBCOMMANDS=$(ls ../subcommands)
for subcommand in $SUBCOMMANDS
do
  addUsage $(basename $subcommand .sh)
done

