# Copyright Contributors to the Open Cluster Management project
apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  registrationImagePullSpec: {{ .Hub.ImageRegistryName }}/registration:{{ .Hub.ReleaseVersion }}
  workImagePullSpec: {{ .Hub.ImageRegistryName }}/work:{{ .Hub.ReleaseVersion }}
