# Copyright Contributors to the Open Cluster Management project
apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  registrationImagePullSpec: {{ .Hub.Registry }}/registration:{{ .BundleVersion.RegistrationImageVersion }}
  workImagePullSpec: {{ .Hub.Registry }}/work:{{ .BundleVersion.WorkImageVersion }}
  placementImagePullSpec: {{ .Hub.Registry }}/placement:{{ .BundleVersion.PlacementImageVersion }}
  {{if .BundleVersion.AddonManagerImageVersion}}
  addOnManagerImagePullSpec: {{ .Hub.Registry }}/addon-manager:{{ .BundleVersion.AddonManagerImageVersion }}
  {{end}}
  deployOption:
    mode: Default
  {{if .RegistrationFeatures}}
  registrationConfiguration:
    {{if .AutoApprove}}
    autoApproveUsers:
    - system:bootstrap:bootstrap-token-{{ .Hub.TokenID }}
    - system:serviceaccount:open-cluster-management:cluster-bootstrap
    {{end}}
    featureGates:
    {{range .RegistrationFeatures }}
    - feature: {{ .Feature }}
      mode: {{ .Mode }}
    {{end}}
  {{end}}
  {{if .WorkFeatures}}
  workConfiguration:
    featureGates:
    {{range .WorkFeatures }}
    - feature: {{ .Feature }}
      mode: {{ .Mode }}
    {{end}}
  {{end}}
  {{if .AddonFeatures}}
  addOnManagerConfiguration:
    featureGates:
    {{range .AddonFeatures }}
    - feature: {{ .Feature }}
      mode: {{ .Mode }}
    {{end}}
  {{end}}
