# Copyright Contributors to the Open Cluster Management project
apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  registrationImagePullSpec: {{ .Hub.Image.Registry }}/registration:{{ .Hub.Image.Tag }}
  workImagePullSpec: {{ .Hub.Image.Registry }}/work:{{ .Hub.Image.Tag }}
