# Copyright Contributors to the Open Cluster Management project
apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  registrationImagePullSpec: {{ .Hub.Registry }}/registration:{{ .BundleVersion.RegistrationImageVersion }}
  workImagePullSpec: {{ .Hub.Registry }}/work:{{ .BundleVersion.WorkImageVersion }}
  placementImagePullSpec: {{ .Hub.Registry }}/placement:{{ .BundleVersion.PlacementImageVersion }}
  deployOption:
    mode: Default
  registrationConfiguration:
    featureGates:
    {{- range .RegistrationFeatures }}
    - feature: {{ .Feature }}
      mode: {{ .Mode }}
    {{- end}}
  workConfiguration:
    featureGates:
    {{- range .WorkFeatures }}
    - feature: {{ .Feature }}
      mode: {{ .Mode }}
    {{- end}}
