# Copyright Contributors to the Open Cluster Management project
apiVersion: v1
kind: Secret
metadata:
  name: external-managed-kubeconfig
  namespace: {{ .AgentNamespace }}
type: Opaque
data:
  kubeconfig: {{ .ManagedKubeconfig }}
