# Copyright Contributors to the Open Cluster Management project

apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
    {{ if eq .managedClusterName "local-cluster" }}
    local-cluster: "true"
    {{ end }}
  name: {{ .managedClusterName }}
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
