# Copyright Contributors to the Open Cluster Management project
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: {{.SampleAppName}}-placement
  namespace: {{.Namespace}}
spec:
  numberOfClusters: 1
  clusterSets:
    - app-{{.SampleAppName}}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            placement: sampleapp
