# Copyright Contributors to the Open Cluster Management project

{{ $needed := (printf "%s%s" .managedCluster.kubeConfig .managedCluster.token) }}
{{ if not (eq $needed "" "%!s(<nil>)" "%!s(<nil>)%!s(<nil>)" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: "{{ .managedCluster.name }}"
stringData:
  autoImportRetry: "{{ .managedCluster.autoImportRetry }}"
{{ if .managedCluster.kubeConfig }}
  kubeconfig: |- 
{{ .managedCluster.kubeConfig | indent 4 }}
{{ end }}
{{ if .managedCluster.token }}
  token: {{ .managedCluster.token }}
  server: {{ .managedCluster.server }}
{{ end }}
type: Opaque
{{ end }}
