# Copyright Contributors to the Open Cluster Management project
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: {{ .AddonName }}
  namespace: {{ .ClusterName }}
spec:
  installNamespace: {{ .NameSpace }} 