# Copyright Contributors to the Open Cluster Management project
apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: {{ .Klusterlet.Name }}
spec:
  deployOption:
    mode: {{ .Klusterlet.Mode }}
  registrationImagePullSpec: {{ .Registry }}/registration:{{ .BundleVersion.RegistrationImageVersion }}
  workImagePullSpec: {{ .Registry }}/work:{{ .BundleVersion.RegistrationImageVersion }}  
  clusterName: {{ .ClusterName }}
  namespace: {{ .Klusterlet.KlusterletNamespace }} 
  externalServerURLs:
  {{ if .Klusterlet.APIServer }}
  - url: {{ .Klusterlet.APIServer }}
  {{ end }}
  registrationConfiguration:
    featureGates:
    {{- range .RegistrationFeatures }}
    - feature: {{ .Feature }}
      mode: {{ .Mode }}
    {{- end}}
  workConfiguration:
    featureGates:
    {{- range .WorkFeatures }}
    - feature: {{ .Feature }}
      mode: {{ .Mode }}
    {{- end}}
    # Uncomment the following configuration lines to add hostAliases for hub api server, 
    # if the server field in your hub cluster kubeconfig is a domain name instead of an ipv4 address.
    # For example, https://xxx.yyy.zzz.
    # This configuration is used for registration-agent and work-agent to communicate with hub api server.
    # hubApiServerHostAlias:
    # ip: "1.2.3.4"
    # hostname: "xxx.yyy.zzz"
