# Copyright Contributors to the Open Cluster Management project
apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: klusterlet
spec:
  registrationImagePullSpec: {{ .ImageRegistry.Registry }}/registration:{{ .ImageRegistry.Version }}
  workImagePullSpec: {{ .ImageRegistry.Registry }}/work:{{ .ImageRegistry.Version }}
  clusterName: {{ .ClusterName }}
  namespace: open-cluster-management-agent
  externalServerURLs:
  {{ if .Klusterlet.APIServer }}
  - url: {{ .Klusterlet.APIServer }}
  {{ end }}
