# Copyright Contributors to the Open Cluster Management project
apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: klusterlet
spec:
  registrationImagePullSpec: {{ .ImageRegistry.Registry }}/registration
  workImagePullSpec: {{ .ImageRegistry.Registry }}/work
  clusterName: {{ .ClusterName }}
  namespace: open-cluster-management-agent
  externalServerURLs:
  - url: {{ .Hub.APIServer }}
