# Copyright Contributors to the Open Cluster Management project
kind: Deployment
apiVersion: apps/v1
metadata:
  name: klusterlet
  namespace: open-cluster-management
  labels:
    app: klusterlet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klusterlet
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: klusterlet
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              topologyKey: failure-domain.beta.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - klusterlet
          - weight: 30
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - klusterlet
      serviceAccountName: klusterlet
      containers:
      - name: klusterlet
        image: {{ .Registry }}/registration-operator:{{ .BundleVersion.OperatorImageVersion }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        args:
          - "/registration-operator"
          - "klusterlet"
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 2
        {{- if or (eq .ResourceRequirement.Type "Default") (eq .ResourceRequirement.Type "") }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        {{- end }}
        {{- if eq .ResourceRequirement.Type "BestEffort" }}
        resources: {}
        {{- end }}
        {{- if eq .ResourceRequirement.Type "ResourceRequirement" }}
        resources:
          {{ .ResourceRequirement.ResourceRequirements | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: tmpdir
          mountPath: /tmp
      volumes:
      - name: tmpdir
        emptyDir: { }
      # Uncomment the following configuration lines to add hostAliases for hub api server, 
      # if the server field in your hub cluster kubeconfig is a domain name instead of an ipv4 address.
      # For example, https://xxx.yyy.zzz.
      # hostAliases:
      # - hostnames:
        # set the target hostname
        # - xxx.yyy.zzz 
        # set the target ipv4 address
        # ip: 1.2.3.4
