name: FOSSA License Scan

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run FOSSA Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
