# Copyright Contributors to the Open Cluster Management project
name: FOSSA License Scan

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'open-cluster-management-io'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7
        with:
          persist-credentials: false
      - name: Run FOSSA Scan
        uses: fossas/fossa-action@29693cc50323968e039056be419b32989fc5880c #v2
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
