# Copyright Contributors to the Open Cluster Management project

name: Go

on:
  push:
    branches: [ main, release-* ]
  pull_request:
    branches: [ main, release-* ]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7
        with:
          go-version-file: go.mod
      - name: verify
        run: make verify

  unit-test:
    runs-on: ubuntu-latest
    env:
      GOPATH: /tmp/go
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7
      with:
        persist-credentials: false
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7
      with:
        go-version-file: go.mod
    - name: Create GOPATH src directory
      run: mkdir -p $GOPATH/src/github.com/open-cluster-management
    - name: Copy the code into the GOPATH
      run: cp -r . $GOPATH/src/github.com/open-cluster-management/clusteradm
    - name: Unit Tests
      working-directory: ${{ env.GOPATH }}/src/github.com/open-cluster-management/clusteradm
      run: make test

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7
      with:
        persist-credentials: false
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7
      with:
        go-version-file: go.mod
    - name: Integration Tests
      run: make test-integration
  
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7
      with:
        persist-credentials: false
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7
      with:
        go-version-file: go.mod
    - name: E2E Tests
      run: |
        BUNDLE_VERSION=$([[ "${{ github.base_ref }}" == "main" ]] && echo latest || echo default) \
        make test-e2e
