# Copyright Contributors to the Open Cluster Management project

name: Verify

on:
  push:
    branches: [ main, release-* ]
  pull_request:
    branches: [ main, release-* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Verify
      run: |
        go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.31.0
        golangci-lint run -E gofmt

